### ISSUE TITLE
Cant get wallaby to run

### ISSUE THREAD

**Issue by MikeFielden** [wallabyjs/wallaby-node-iojs-sample#1]
I cannot seem to get wallaby to run at all. Everything I try gives me an error. I have gone through the getting started post many times. I dont think I am missing something. Perhaps you can see something?

I have a file called `wallaby.config.js` in the root of the project with the following: 

```
module.exports = function () {
  return {
    "files": [
      "**/*.js",
      "!test/*.js"
    ],

    "tests": [
      "test/*Spec.js"
    ],

    "testFramework": "mocha@2.1.0",

    "env": {
      "type": "node",
      "params": {
        runner: "--harmony"
      }
    }
  }
}
```

When I try to start wallaby i get the following erorr: 

`
Failed to parse node_modules/babel/node_modules/babel-core/node_modules/js-tokens/test/fixtures/regex.js, SyntaxError: Unexpected token (22:3)
  at emitTwo (events.js:87:13)
  at process.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)
`

What am I doing wrong?

**Comment by ArtemGovorov** [comment]
Hello,

Your files list pattern `**/*.js` includes node_modules (and everything else in the project folder and all subfolders), so wallaby tries to copy it to its local cache and instrument them as well and that's not desirable at all.

One solution would be to specify the source folder, that you probably have, like 

``` JavaScript
"files": [
      "lib/**/*.js" // or `src` or whatever the folder with your source code is named
    ]
```

This way you won't have to exclude tests pattern.

Alternatively, you may just exclude node_modules, just like you have excluded tests folder.

``` JavaScript
"files": [
      "**/*.js",
      "!test/*.js",
      "!node_modules/**/*.js"
    ]
```

Please let me know if it helps.

**Comment by MikeFielden** [comment]
I figured it out after some trial and error :) Thanks for your help!
